export const allTags = [
  "Technology",
  "Programming",
  "Innovation",
  "Arts",
  "Creative",
  "Design",
  "Music",
  "Performance",
  "Sports",
  "Fitness",
  "Competition",
  "Business",
  "Entrepreneurship",
  "Networking",
  "Environment",
  "Sustainability",
  "Community",
  "AI",
  "Web Development",
  "Painting",
  "Digital Art",
  "Instruments",
  "Production",
  "Team Sports",
  "Wellness",
  "Finance",
  "Startups",
  "Conservation",
  "Awareness",
  "Robotics",
  "Engineering",
  "Automation",
  "Cybersecurity",
  "Ethical Hacking",
  "Network Security",
]
